### ISSUE TITLE
Snap may not include QT5Charts

### ISSUE THREAD

**Issue by wd5gnr** [lxi-tools/lxi-tools#17]
Tried the snap, screenshots failed (core dump). This is on current KDE Neon.

So I tried to do a build. ./configure tells me QT5Charts is not installed. So I did that. 

Even after --enable-lxi-gui, the Makefile doesn't build it. 

Go to gui directory:
qmake
make

Now I get a lot of missing problems related to QT5Charts

qmake reports Qt version 5.11.2

Any thoughts?

**Comment by lundmar** [comment]
Hmm, the snap used to work fine. Something has changed in the snap build or run time environment. I'll look into it.

I'm not sure what goes wrong on your system and why it does not pick up on it. Maybe try a clean before running the --enable-lxi-gui flag.

**Comment by wd5gnr** [comment]
Tried several things. No dice.
qtchooser -print-env:
QT_SELECT="default"
QTTOOLDIR="/usr/lib/qt5/bin"
QTLIBDIR="/usr/lib/x86_64-linux-gnu"

qmake -v
QMake version 3.1
Using Qt version 5.11.2 in /usr/lib/x86_64-linux-gnu

Libs:
-rw-r--r-- 1 root root    1111 Oct 20 11:05 /usr/lib/x86_64-linux-gnu/libQt5Charts.prl
lrwxrwxrwx 1 root root      22 Oct 20 11:05 /usr/lib/x86_64-linux-gnu/libQt5Charts.so -> libQt5Charts.so.5.11.2
lrwxrwxrwx 1 root root      22 Oct 20 11:05 /usr/lib/x86_64-linux-gnu/libQt5Charts.so.5 -> libQt5Charts.so.5.11.2
lrwxrwxrwx 1 root root      22 Oct 20 11:05 /usr/lib/x86_64-linux-gnu/libQt5Charts.so.5.11 -> libQt5Charts.so.5.11.2
-rw-r--r-- 1 root root 1779752 Oct 20 11:05 /usr/lib/x86_64-linux-gnu/libQt5Charts.so.5.11.2

It dies on the link step unable to find a bunch of classes in QtCharts. note -lQt5Charts is there:

g++ -Wl,-O1 -o lxi-gui main.o mainwindow.o workerthread.o qrc_lxi-gui.o moc_mainwindow.o moc_workerthread.o   
-llxi ../../libapp.a -lreadline -L -lQt5Charts -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread                 
mainwindow.o: In function `MainWindow::on_pushButton_DataRecorder_Start_clicked()':                           
mainwindow.cpp:(.text+0x20ce): undefined reference to `QtCharts::QXYSeries::count() const'                    
mainwindow.cpp:(.text+0x20db): undefined reference to `QtCharts::QXYSeries::count() const'                    
mainwindow.cpp:(.text+0x2152): undefined reference to `QtCharts::QXYSeries::clear()'                          
mainwindow.cpp:(.text+0x215b): undefined reference to `QtCharts::QXYSeries::clear()'
mainwindow.cpp:(.text+0x2173): undefined reference to `QtCharts::QValueAxis::setRange(double, double)'
mainwindow.cpp:(.text+0x218b): undefined reference to `QtCharts::QValueAxis::setRange(double, double)'
mainwindow.o: In function `MainWindow::DataRecorder_Update()':
mainwindow.cpp:(.text+0x24ab): undefined reference to `QtCharts::QXYSeries::append(double, double)'
mainwindow.cpp:(.text+0x2588): undefined reference to `QtCharts::QValueAxis::setMax(double)'
mainwindow.cpp:(.text+0x259b): undefined reference to `QtCharts::QValueAxis::max() const'
mainwindow.cpp:(.text+0x25b9): undefined reference to `QtCharts::QValueAxis::setMax(double)'
mainwindow.cpp:(.text+0x25c5): undefined reference to `QtCharts::QValueAxis::applyNiceNumbers()'
mainwindow.cpp:(.text+0x25d7): undefined reference to `QtCharts::QValueAxis::setMax(double)'
mainwindow.cpp:(.text+0x26c6): undefined reference to `QtCharts::QXYSeries::append(double, double)'
mainwindow.o: In function `MainWindow::DataRecorder_zoomOut()':
(more redacted for space)

**Comment by lundmar** [comment]
It may have to do with the version of qt5charts in play. For the snap build I see we are using release-2.1.0 tag. 

https://github.com/lxi-tools/lxi-tools.snapcraft/blob/master/snap/snapcraft.yaml

**Comment by lundmar** [comment]
Have you tried latest lxi-tools edge snap? It is working fine on my Ubuntu 18.10 system.

**Comment by wd5gnr** [comment]
snap refresh says I'm up to date but the problem persists. I have a very large screen, I wonder if that could be it? I did try running it in Xephyr as a test, but that didn't work.

**Comment by lundmar** [comment]
What Linux distribution are you running there?

**Comment by wd5gnr** [comment]
Latest version of KDE Neon which is Ubuntu based. Xanmod kernel. NVidia 390 drivers. If I had to guess it is the screen size or NVidia that is killing it.

**Comment by lundmar** [comment]
It only crashes when you try take instrument screenshot right?

It might be related to window size and how it tries to upscale the screenshot in case of large size window. If so, please try run in a smaller window and take screenshot.

Also, make sure you are running --edge when u install snap. I've rebuilt the snaps recently to make sure all components are up to date.

**Comment by wd5gnr** [comment]
Sorry, I'm not much of a snap user. I did the --edge and also did a small window and got the same result each time. I'd dig into the core dump if I knew how to unlock it out of the snap.

**Comment by maik-dmxc** [comment]
LXI-tools crashes when doing liveview or screenshot
installt with
`snap install lxi-tools`
and 
`snap refresh --edge lxi-tools`

also the Data Recorder is not working, there are two messages wenn i try to start it.
`Failed to receive message!`

running 18.04
RIGOL TECHNOLOGIES,DS1104Z,DS1ZA184050424,00.04.04.SP1

regards maik

**Comment by kk6olf** [comment]
I too am having a similar problem with screenshots or liveview.  
I can run SCPI commands through the lxi-gui no problem.  
I can also take screenshots from the command line without any problem using: 
         lxi screenshot -p siglent-sds -a 192.168.1.17 test

But when I go to take a screenshot using the gui the application quits leaving the following message in syslog:

Mar 12 23:39:33 yoga kernel: [11810.348074] lxi-gui[16744]: segfault at 0 ip 00000000004176cb sp 00007ffcdd335720 error 4 in lxi-gui[400000+27000]

I'm running lxi-gui 1.21 (BETA)  (I've tried snap with/without --edge, and the the Ubuntu repo - same results)
Scope ID: Siglent Technologies,SDS1202X-E,SDS1ECDD2R8819,8.1.1.3.23
Ubuntu 18.04 LTS
Intel® Core™ i7-8550U CPU @ 1.80GHz × 8 
Intel® UHD Graphics 620 (Kabylake GT2)  (Screen resolution is set to 3840x2160)

**Comment by lundmar** [comment]
Bug fixed in 85e3ff292ebdcec51474be550a267345b06326b8
